### ISSUE TITLE
Page name from previous URL

### ISSUE THREAD

**Issue by sergical** [okgrow/auto-analytics#10]
I am using `react-helmet` and setting a `title` for each page within `render`

Here's a snippet from Segments' debugger

```
analytics.page('Sign Up | Instant Outreach', {
  name: 'Sign Up | Instant Outreach',
  path: '/login',
  referrer: 'http://localhost:3000/signup',
  search: '',
  title: 'Sign Up | Instant Outreach',
  url: 'http://localhost:3000/login'
});
```

This was me going from `/signup` to `/login` - as you can see the path is correct, the referrer is correct, the url is correct however name and title are from previous path.

Thoughts? 👍

**Comment by cfnelson** [comment]
@416serg `Analytics.js` is reporting the `page` event before `react-helmet` is able to update the `document.title`. Having `Helmet` deeply nested in your DOM will cause a delay in execution. I would try to move `Helmet` as high up in your DOM tree as possible so it can execute sooner. 

- What version of `react-helmet` are you using? I recall other users reporting v4.0.0 is faster then v5.0.0 (unsure if they resolved that issue).
- Are you able to show how you are currently using `Helmet` in your `render()`?

I will try to set some time aside tomorrow to investigate a solution and see if we should make any changes to the package to better handle `react-helmet` usage.

**Comment by sergical** [comment]
@cfnelson `"react-helmet": "^5.2.0",` - I can try `4.0.0` but I think it's more about it being deep in my DOM.

```
import React from 'react';
import { Alert } from 'react-bootstrap';
import { Helmet } from "react-helmet";

const NotFound = () => (
  <div className="NotFound" style={{marginTop: 71}}>
    <Helmet>
      <title>Not Found (404) | Instant Outreach</title>
    </Helmet>
    <Alert bsStyle="danger">
      <p><strong>Error [404]</strong>: {window.location.pathname} does not exist.</p>
    </Alert>
  </div>
);

export default NotFound;
```

^ Example of a page using it and here's my `App.js`

```
const App = props => (
  <Router>
    {!props.loading ? <div className="App">
      <Navigation {...props} />
      <Grid fluid>
        <Row>
          <Switch>
            <Route exact name="index" path="/" component={Index} {...props} />
            <Route component={NotFound} />
          </Switch>
        </Row>
      </Grid>
      <Footer />
    </div> : ''}
  </Router>
);
```

Thanks!

**Comment by sergical** [comment]
Also tried changing `App.js` to

```
const App = props => (
  <Router>
    {!props.loading ? <div className="App">
      <Navigation {...props} />
      <Grid fluid>
        <Row>
          <Helmet
            titleTemplate="%s | Instant Outreach"
          />
          <Switch>
            <Route exact name="index" path="/" component={Index} {...props} />
            <Route component={NotFound} />
          </Switch>
        </Row>
      </Grid>
      <Footer />
    </div> : ''}
  </Router>
);
```

But still the same behaviour within Segment 😞

**Comment by sergical** [comment]
Also, not getting automatic `identify` calls :/

**Comment by cfnelson** [comment]
@416serg I `identify ` calls are not automatic in this repo as it's `meteor` agnostic. You will have to manually set them up yourself. In regards to `react-helmet` I looked at an implementation I had previously working and I can see the same behaviour occurring as you reported.

I will need to investigate when this changed, but the issue is down to `react-helmet` updating the `document.title` after the analytics has already captured the page event. Related discussion [here](https://github.com/nfl/react-helmet/issues/189).

**Comment by sergical** [comment]
@cfnelson thanks for pointing that out! How would you suggest setting up `analytics.identify` in this case? 

Downgrading to `4.0.0` didn't fix it for me either 😢

**Comment by cfnelson** [comment]
@416serg If `v4.0.0` isn't working then will see if we can place an optional delay on logging the page view. As a temp solution you could also try setting the `document.title` directly after route change in your page components instead of `react-helmet`. 

For `analytics.identify` you can look at the Meteor package which we have that does this automatically. See here for the [client side](https://github.com/okgrow/analytics/blob/master/client/main.js), and [server side](https://github.com/okgrow/analytics/blob/master/server/publications.js). If you are not using Meteor or using some other accounts system, you need to call `identify` when your login event occurs.

**Comment by sergical** [comment]
Closing this for now then, thanks for your help!

**Comment by cfnelson** [comment]
@416serg Thanks for raising this issue! Inspired me to investigate and solve the issue with `react-helmet`. I have just published `v1.0.3` which contains to back-ported fixes from the `v2.0.0` branch. This version should work with `react-helmet` correctly (tested against the example). 

The `document.title` will now be the current page and not the previous. Also wrote a fix for a bug I noticed with the `referrer` when using the browsers back/fwd buttons. Let me know if it works for you and solves your issues!

Planning to publish `v2.0.0` this week, when it does get released I would recommend upgrading & following the instructions as it will reduce bundle size of the package. 🔥

**Comment by sergical** [comment]
@cfnelson any chance this will also get implemented into `okgrow:analytics` Meteor package? Going to be using that for now since the `identify` calls happens automatically.

**Comment by cfnelson** [comment]
@416serg new meteor version should be up now. We just published to atmosphere today.  Hopefully have the v2 major released soon as well so you can include only the specific integrations that you want to use.

**Comment by sergical** [comment]
this will be `okgrow:analytics@3.0.2` right? thanks!
