### ISSUE TITLE
Setting Hash Triggers PopState without State

### ISSUE THREAD

**Issue by arist0tl3** [okgrow/auto-analytics#16]
Hey again @cfnelson :)

I ran into another scenario where I'm hitting referrer errors when setting a hash:

```
window.location.hash = "about";
```

Setting the hash triggers the following `popstate` event, with a null `window.history.state`:

```
window.addEventListener('popstate', () => {
    // NOTE: A delay is added as document.title wont be updated yet if packages
    // like react-helmet or react-document-title, etc... are used.
    logPageLoad({ referrer: window.history.state.referrer, delay: 50 });
  }, false);
```

Which throws: `Uncaught TypeError: Cannot read property 'referrer' of null`

My initial thought:

```
window.addEventListener('popstate', () => {
    // NOTE: A delay is added as document.title wont be updated yet if packages
    // like react-helmet or react-document-title, etc... are used.
    const { state }  = window.history;
    const referrer = state && state.referrer ? state.referrer : null;
    logPageLoad({ referrer, delay: 50 });
  }, false);
```

Honestly, I don't know the analytics API well enough to know if passing `null` as the `referrer` is the best option. Happy to open a PR if it makes sense!

**Comment by cfnelson** [comment]
@arist0tl3 Instead of `null` I would suggest an empty string `''`. This would be in line with the behaviour of when you add a `rel="noreferrer"` to your link or visiting the page via a bookmark the `document.referrer` is an empty string. You could also turn your two line fix into one line like this ->  
```js 
const { referrer = '' } = window.history.state || {};
logPageLoad({ referrer: referrer || '', delay: 50 });
```
Would be happy to accept a PR for this, maybe if you could add a comment above stating this is to handle when state is null or someone else destroys the state.

**Comment by cfnelson** [comment]
Has been resolved with PR https://github.com/okgrow/auto-analytics/pull/17
